ifneq ($(BUILD_KERNEL),true)
ifneq ($(TARGET_PREBUILT_KERNEL),)
LOCAL_PRIVATE_PATH := device/xiaomi/aries/kernel

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ
TARGET_PREBUILT_KERNEL_INCLUDE:=$(KERNEL_OUT)
$(TARGET_PREBUILT_KERNEL_INCLUDE):
	echo $(LOCAL_PRIVATE_PATH) $(TARGET_PREBUILT_KERNEL)
	mkdir -p $(KERNEL_OUT)
	-cp -rf $(LOCAL_PRIVATE_PATH)/include/* $(KERNEL_OUT)/
else
TARGET_PREBUILT_KERNEL_INCLUDE:=
endif
endif
