#ifndef _VOICEPROC_H
#define _VOICEPROC_H

struct voiceproc_img
{
	unsigned char *buf;
	unsigned img_size;
};

#define VOICEPROC_IOCTL_MAGIC		';'
#define VOICEPROC_BOOTUP_INIT		_IOW(VOICEPROC_IOCTL_MAGIC, 1, struct voiceproc_img *)
#define VOICEPROC_SET_CONFIG		_IOW(VOICEPROC_IOCTL_MAGIC, 2, unsigned int *)
#define VOICEPROC_SET_PARAM		_IOW(VOICEPROC_IOCTL_MAGIC, 4, struct VOICEPROC_config_data *)
#define VOICEPROC_SYNC_CMD		_IO(VOICEPROC_IOCTL_MAGIC, 9)
#define VOICEPROC_SLEEP_CMD		_IO(VOICEPROC_IOCTL_MAGIC, 11)
#define VOICEPROC_RESET_CMD		_IO(VOICEPROC_IOCTL_MAGIC, 12)
#define VOICEPROC_WAKEUP_CMD		_IO(VOICEPROC_IOCTL_MAGIC, 13)
#define VOICEPROC_MDELAY		_IOW(VOICEPROC_IOCTL_MAGIC, 14, unsigned int)
#define VOICEPROC_READ_FAIL_COUNT	_IOR(VOICEPROC_IOCTL_MAGIC, 15, unsigned int *)
#define VOICEPROC_READ_SYNC_DONE	_IOR(VOICEPROC_IOCTL_MAGIC, 16, bool *)
#define VOICEPROC_READ_DATA		_IOR(VOICEPROC_IOCTL_MAGIC, 17, unsigned)
#define VOICEPROC_WRITE_MSG		_IOW(VOICEPROC_IOCTL_MAGIC, 18, unsigned)
#define VOICEPROC_SET_PRESET		_IOW(VOICEPROC_IOCTL_MAGIC, 19, unsigned)

#define PRESET_BASE 0x80310000
#define ES310_PRESET_HANDSET_INCALL_NB		(PRESET_BASE)
#define ES310_PRESET_HEADSET_INCALL_NB		(PRESET_BASE + 1)
#define ES310_PRESET_HANDSFREE_REC_NB		(PRESET_BASE + 2)
#define ES310_PRESET_HANDSFREE_INCALL_NB	(PRESET_BASE + 3)
#define ES310_PRESET_HANDSET_INCALL_WB		(PRESET_BASE + 4)
#define ES310_PRESET_HEADSET_INCALL_WB		(PRESET_BASE + 5)
#define ES310_PRESET_AUDIOPATH_DISABLE		(PRESET_BASE + 6)
#define ES310_PRESET_HANDSFREE_INCALL_WB	(PRESET_BASE + 7)
#define ES310_PRESET_HANDSET_VOIP_WB		(PRESET_BASE + 8)
#define ES310_PRESET_HEADSET_VOIP_WB		(PRESET_BASE + 9)
#define ES310_PRESET_HANDSFREE_REC_WB		(PRESET_BASE + 10)
#define ES310_PRESET_HANDSFREE_VOIP_WB		(PRESET_BASE + 11)
#define ES310_PRESET_VOICE_RECOGNIZTION_WB	(PRESET_BASE + 12)

enum ES310_PathID {
	ES310_PATH_SUSPEND = 0,
	ES310_PATH_HANDSET,
	ES310_PATH_HEADSET,
	ES310_PATH_HANDSFREE,
	ES310_PATH_BACKMIC,
	ES310_PATH_MAX
};
#endif /* _VOICEPROC_H */
